const fs = require('fs-extra');
const path = require('path');
const { ImplementationPlan } = require('../Contract');
const NexusClock = require('../NexusClock');
const BasePhase = require('./BasePhase');
const NexusError = require('../NexusError');

class PlanningPhase extends BasePhase {
    async run(auditReport) {
        const report = auditReport || this.engine.currentAudit;
        if (!report) {
            throw new NexusError('PLANNING', 'Pipeline Violation: Planning requires a valid Audit Report.');
        }

        this.log(`📅 Phase 2: Planning based on ${report.id}...`, 'info');
        
        const planID = `PLAN-${Date.now()}`;
        const tasks = report.findings
            .filter(f => f.severity !== 'INFO' || !f.message.includes('Audit completed'))
            .map((f, i) => {
                const task = {
                    id: i + 1,
                    description: `${f.severity}: ${f.message}`,
                    status: 'pending',
                    rationale: f.rationale || 'Tidak ada keterangan tambahan.',
                    recommendation: f.recommendation || 'Gunakan praktik terbaik standar industri.'
                };

                // AUTO-ACTION GENERATION
                if (f.message.includes('.env detected')) {
                    task.action = {
                        type: 'FILE_APPEND',
                        target: '.gitignore',
                        content: '.env'
                    };
                    task.description += ' (Auto-fix enabled)';
                }

                return task;
            });

        // 🌐 GRAPHRAG ENRICHMENT: Ground planning recommendations with Obsidian knowledge
        for (const task of tasks) {
            try {
                if (this.engine.searchKnowledgeGraph) {
                    const query = task.description.replace(/^(CRITICAL|WARNING|ERROR|INFO):\s*/i, "").slice(0, 80);
                    const graphMatch = await this.engine.searchKnowledgeGraph(query, {
                        topK: 1,
                        maxHops: 1,
                        maxNeighborsPerSeed: 2,
                        maxTotalChars: 800,
                    });
                    if (graphMatch && graphMatch.seeds && graphMatch.seeds.length > 0) {
                        const seed = graphMatch.seeds[0];
                        const relNote = graphMatch.connectedNotes?.[0]?.node?.title;
                        const relText = relNote ? ` ➔ linked to [[${relNote}]]` : "";
                        task.recommendation += ` [Vault: [[${seed.title}]]${relText}]`;
                    }
                }
            } catch (_) {}
        }

        const plan = new ImplementationPlan(planID, report.id, tasks);
        this.engine.currentPlan = plan;

        await fs.ensureDir(this.engine.planningPath);
        await fs.writeJson(path.join(this.engine.planningPath, `plan_${planID}.json`), plan.toJSON(), { spaces: 2 });
        
        const mdPlan = `
# 🛠 Implementation Plan: ${planID}
**Ref Audit**: [${report.id}](../audit/audit_SUMMARY_${report.id}.md)
**Status**: Ready for Execution

---

## 📋 Task List & Learning Insights
${tasks.map(t => `
### [ ] Task ${t.id}: ${t.description}
- **🧐 Why?**: ${t.rationale}
- **💡 Action**: ${t.recommendation}
`).join('\n')}

---
*Generated by Nexus Orchestrator*
        `;
        await fs.writeFile(path.join(this.engine.planningPath, `plan_${planID}.md`), mdPlan);

        this.log(`✅ Plan Created: ${planID}`, 'success');
        return plan;
    }
}

module.exports = PlanningPhase;
