const EvolutionPiper = require('../../agent/core/EvolutionPiper');
const NexusEngine = require('../../agent/core/NexusEngine');
const fs = require('fs-extra');
const path = require('path');

const PHASE_1_PROJECTS = [
    { name: 'todo-app-realtime', tags: ['crud', 'auth', 'basic', 'phase-1'] },
    { name: 'notes-app-tagging', tags: ['crud', 'auth', 'basic', 'phase-1'] },
    { name: 'bookmark-manager', tags: ['crud', 'auth', 'basic', 'phase-1'] },
    { name: 'habit-tracker', tags: ['crud', 'auth', 'basic', 'phase-1'] },
    { name: 'expense-tracker', tags: ['crud', 'auth', 'basic', 'phase-1'] },
    { name: 'daily-journal', tags: ['crud', 'auth', 'basic', 'phase-1'] },
    { name: 'contact-manager', tags: ['crud', 'auth', 'basic', 'phase-1'] },
    { name: 'password-manager-ui', tags: ['crud', 'auth', 'basic', 'phase-1'] },
    { name: 'personal-portfolio', tags: ['crud', 'auth', 'basic', 'phase-1'] }
];

async function runPhase1AutonomousTesting() {
    console.log('🚀 Memulai Autonomous Testing untuk Phase 1: Fundamental CRUD & Auth Projects\n');
    const rootPath = process.cwd();
    const piper = new EvolutionPiper(rootPath);
    
    for (const project of PHASE_1_PROJECTS) {
        console.log(`\n======================================================`);
        console.log(`🧪 TESTING PROJECT: ${project.name}`);
        console.log(`🏷️ Tags: ${project.tags.join(', ')}`);
        console.log(`======================================================`);
        
        try {
            // 1. Spawning Sandbox
            const sandboxPath = await piper.spawnSandbox(project.name, 'crud');
            
            // Inject dummy Nexus environment for the engine to recognize it
            const nexusConfigPath = path.join(sandboxPath, 'nexus');
            await fs.ensureDir(nexusConfigPath);
            await fs.writeFile(path.join(sandboxPath, 'README.md'), `# ${project.name}\nGenerated by Phase-1 Autonomous Testing.`);
            
            // 2. Initialize Nexus Engine for the spawned sandbox
            console.log(`🤖 Menginisiasi NexusEngine pada sandbox: ${project.name}`);
            const engine = new NexusEngine({ rootPath: sandboxPath });
            
            // 3. Run Autonomous Cycle (Audit -> Plan -> Execute -> Verify)
            console.log(`⏳ Memulai siklus Nexus (Learning Mode)...`);
            
            // Overriding prompt behavior for testing: auto approve everything
            const originalAsk = process.stdin;
            
            await engine.runCycle({ mode: 'learning', allowSensitive: true });
            
            // 4. Harvesting Wisdom (Learning Absorption)
            console.log(`🌾 Menyerap insight pengetahuan (Harvesting) ke Golden HUB...`);
            await engine.harvest(sandboxPath);
            
            console.log(`✅ Siklus testing untuk [${project.name}] Selesai.`);
            
        } catch (error) {
            console.error(`❌ Gagal mengeksekusi pipeline pada project [${project.name}]:`, error);
        }
    }
    
    console.log('\n🎉 Seluruh project Phase 1 telah selesai melalui tahap Autonomous Testing!');
}

runPhase1AutonomousTesting().catch(console.error);
