// tests/TDD/phase1_testing.js
// Section 1 — Fundamental CRUD & Auth (9 projects)
// Pipeline: Copy TALL Template → Configure → Migrate → Nexus Cycle → Harvest
// Fixed v2.0: Pakai TALL stack template + resetCycleCounter() per project

const fs = require('fs-extra');
const path = require('path');
const { execSync } = require('child_process');
const NexusEngine = require('../../agent/core/NexusEngine');
const EvolutionPiper = require('../../agent/core/EvolutionPiper');

const TEMPLATE_SOURCE = path.join(__dirname, '..', 'sandboxes', 'url-shortener');
const SANDBOXES_DIR   = path.join(__dirname, '..', 'sandboxes');
const ROOT_PATH       = path.join(__dirname, '..', '..');

const PHASE_1_PROJECTS = [
    { name: 'todo-app-realtime',   tags: ['crud', 'auth', 'realtime', 'phase-1'] },
    { name: 'notes-app-tagging',   tags: ['crud', 'auth', 'tagging',  'phase-1'] },
    { name: 'bookmark-manager',    tags: ['crud', 'auth', 'basic',    'phase-1'] },
    { name: 'habit-tracker',       tags: ['crud', 'auth', 'basic',    'phase-1'] },
    { name: 'expense-tracker',     tags: ['crud', 'auth', 'finance',  'phase-1'] },
    { name: 'daily-journal',       tags: ['crud', 'auth', 'basic',    'phase-1'] },
    { name: 'contact-manager',     tags: ['crud', 'auth', 'basic',    'phase-1'] },
    { name: 'password-manager-ui', tags: ['crud', 'auth', 'security', 'phase-1'] },
    { name: 'personal-portfolio',  tags: ['crud', 'auth', 'basic',    'phase-1'] },
];

async function setupTALLProject(project, piper) {
    const targetPath = path.join(SANDBOXES_DIR, project.name);

    console.log(`\n${'='.repeat(56)}`);
    console.log(`🧪 [SECTION 1] PROJECT: ${project.name}`);
    console.log(`🏷️  Tags: ${project.tags.join(', ')}`);
    console.log(`${'='.repeat(56)}`);

    // ── STEP 1: Backup nexus folder kalau sudah ada knowledge sebelumnya
    const nexusPath   = path.join(targetPath, 'nexus');
    const nexusBackup = path.join(targetPath, '_nexus_backup');
    if (await fs.pathExists(nexusPath)) {
        console.log(`   💾 Backing up existing nexus knowledge...`);
        await fs.copy(nexusPath, nexusBackup);
    }

    // ── STEP 2: Copy TALL stack template (url-shortener sebagai base)
    console.log(`   📂 Copying TALL stack template...`);
    const hasDeps = await fs.pathExists(path.join(targetPath, 'node_modules'));
    await fs.emptyDir(targetPath).catch(e => console.warn(`   ⚠️  Bypass locked files during clean: ${e.message.slice(0,60)}`));
    await fs.copy(TEMPLATE_SOURCE, targetPath, {
        filter: src => {
            if (src.includes(path.join('url-shortener', 'nexus'))) return false;
            if (hasDeps && /(\\|\/)(node_modules|vendor)(\\|\/|$)/.test(src)) return false;
            return true;
        }
    });

    // ── STEP 3: Konfigurasi project-spesifik
    console.log(`   ⚙️  Configuring environment...`);
    const envPath = path.join(targetPath, '.env');
    if (await fs.pathExists(envPath)) {
        let env = await fs.readFile(envPath, 'utf8');
        env = env.replace(/APP_NAME=.*/g, `APP_NAME=${project.name}`);
        await fs.writeFile(envPath, env);
    }

    // ── STEP 4: Restore nexus knowledge kalau ada backup
    if (await fs.pathExists(nexusBackup)) {
        console.log(`   🧠 Restoring previous nexus knowledge...`);
        await fs.copy(nexusBackup, nexusPath);
        await fs.remove(nexusBackup);
    } else {
        await fs.ensureDir(nexusPath);
    }

    // ── STEP 5: Inject README project-spesifik
    await fs.writeFile(
        path.join(targetPath, 'README.md'),
        `# ${project.name}\nSection 1 (Fundamental CRUD & Auth) — TALL Stack Sandbox.\nTags: ${project.tags.join(', ')}\nGenerated by Nexus Autonomous Pipeline.`
    );

    // ── STEP 6: Migrate database (fresh + force)
    console.log(`   🗄️  Migrating SQLite database...`);
    const dbPath = path.join(targetPath, 'database', 'database.sqlite');
    await fs.remove(dbPath).catch(() => {});
    await fs.writeFile(dbPath, '');
    try {
        execSync('php artisan migrate:fresh --force', { cwd: targetPath, stdio: 'ignore' });
        console.log(`   ✅ Database migrated.`);
    } catch (e) {
        console.warn(`   ⚠️  Migrate failed (non-fatal): ${e.message.slice(0, 80)}`);
    }

    // ── STEP 7: Reset cycle counter (guardrail — setiap project = fresh session)
    piper.resetCycleCounter();

    // ── STEP 8: Nexus Autonomous Cycle
    console.log(`   🤖 Starting Nexus Autonomous Cycle (mode: learning)...`);
    const engine = new NexusEngine({ rootPath: targetPath });
    await engine.runCycle({ mode: 'learning', allowSensitive: true });

    // ── STEP 8.5: Clean Code & Stability Verification Loop (5x)
    await engine.cleanCodeAndVerify(targetPath);

    // ── STEP 9: Harvest wisdom ke Golden HUB
    console.log(`   🌾 Harvesting knowledge to Golden HUB...`);
    await engine.harvest(targetPath);

    console.log(`\n🚀 FULL TALL APP READY - ${project.name}`);
    console.log(`📁 Path: ${targetPath}`);
    console.log(`🌐 Akses: http://localhost:8000 (login: admin@example.com / password)`);
    console.log(`💻 Perintah: npm run serve:tall`);
    console.log(`✅ [${project.name}] pipeline complete.\n`);
}

async function runPhase1() {
    console.log('\n╔══════════════════════════════════════════════════════╗');
    console.log('║  🚀 NEXUS — Section 1: Fundamental CRUD & Auth       ║');
    console.log('║  9 Projects | TALL Stack | Parallel Evolution        ║');
    console.log('╚══════════════════════════════════════════════════════╝\n');

    if (!(await fs.pathExists(TEMPLATE_SOURCE))) {
        console.error(`❌ Template TALL stack tidak ditemukan di:\n   ${TEMPLATE_SOURCE}`);
        process.exit(1);
    }

    const piper = new EvolutionPiper(ROOT_PATH);
    const engine = new NexusEngine({ rootPath: ROOT_PATH }); // We use main engine for parallel runner
    const total = PHASE_1_PROJECTS.length;
    let success = 0, failed = 0;
    const startTime = Date.now();

    console.log(`\x1b[35m⚡ Starting Sequential Evolution (One by one)...\x1b[0m`);

    for (const project of PHASE_1_PROJECTS) {
        try {
            await setupTALLProject(project, piper);
            success++;
        } catch (err) {
            console.error(`\n\x1b[31m❌ GAGAL [${project.name}]: ${err.message}\x1b[0m`);
            failed++;
            const logFile = path.join(ROOT_PATH, 'logs', 'sandbox-errors.log');
            await fs.ensureDir(path.dirname(logFile));
            await fs.appendFile(logFile, `[${new Date().toISOString()}] [Section 1] [${project.name}] ${err.message}\n`);
        }
    }

    const totalElapsed = Math.round((Date.now() - startTime) / 1000);

    console.log(`\n${'='.repeat(56)}`);
    console.log(`📊 SECTION 1 SELESAI: ${success} berhasil, ${failed} gagal`);
    console.log(`⏱  Total waktu: ${totalElapsed}s`);
    console.log(`${'='.repeat(56)}\n`);

    if (failed > 0) process.exit(1);
    process.exit(0);
}

runPhase1().catch(err => {
    console.error('❌ Fatal error di phase1_testing.js:', err);
    process.exit(1);
});
