// tests/TDD/setup_dynamic_section.js
// NEXUS DYNAMIC SANDBOX PIPELINE
// Handles Sections 4 through 10 dynamically.

const fs = require('fs-extra');
const path = require('path');
const { execSync } = require('child_process');
const NexusEngine = require('../../agent/core/NexusEngine');
const EvolutionPiper = require('../../agent/core/EvolutionPiper');

const TEMPLATE_SOURCE = path.join(__dirname, '..', 'sandboxes', 'url-shortener');
const SANDBOXES_DIR   = path.join(__dirname, '..', 'sandboxes');
const ROOT_PATH       = path.join(__dirname, '..', '..');

const projectsData = require('./100-projects-data.js');

const sectionArg = process.argv[2];
if (!sectionArg || !projectsData[sectionArg]) {
    console.error(`❌ Harap berikan argumen section yang valid (4-10).`);
    process.exit(1);
}

const sectionConfig = projectsData[sectionArg];

async function setupTALLProject(projectName, piper) {
    const targetPath = path.join(SANDBOXES_DIR, projectName);

    console.log(`\n${'='.repeat(56)}`);
    console.log(`🚀 [SECTION ${sectionArg}] PROJECT: ${projectName}`);
    console.log(`🏷️  Tags: ${sectionConfig.tags.join(', ')}`);
    console.log(`${'='.repeat(56)}`);

    // ── STEP 1: Backup nexus knowledge
    const nexusPath   = path.join(targetPath, 'nexus');
    const nexusBackup = path.join(targetPath, '_nexus_backup');
    if (await fs.pathExists(nexusPath)) {
        console.log(`   💾 Backing up nexus knowledge...`);
        await fs.copy(nexusPath, nexusBackup);
    }

    // ── STEP 2: Copy TALL template (Bypass dependencies EPERM)
    console.log(`   📂 Copying TALL stack template...`);
    const hasDeps = await fs.pathExists(path.join(targetPath, 'node_modules'));
    await fs.emptyDir(targetPath).catch(e => console.warn(`   ⚠️  Bypass locked files during clean: ${e.message.slice(0,60)}`));
    await fs.copy(TEMPLATE_SOURCE, targetPath, {
        filter: src => {
            if (src.includes(path.join('url-shortener', 'nexus'))) return false;
            if (hasDeps && /(\\|\/)(node_modules|vendor)(\\|\/|$)/.test(src)) return false;
            return true;
        }
    });

    // ── STEP 3: Konfigurasi .env
    console.log(`   ⚙️  Configuring environment...`);
    const envPath = path.join(targetPath, '.env');
    if (await fs.pathExists(envPath)) {
        let env = await fs.readFile(envPath, 'utf8');
        env = env.replace(/APP_NAME=.*/g, `APP_NAME=${projectName}`);
        await fs.writeFile(envPath, env);
    }

    // ── STEP 4: Restore nexus knowledge
    if (await fs.pathExists(nexusBackup)) {
        await fs.copy(nexusBackup, nexusPath);
        await fs.remove(nexusBackup);
    } else {
        await fs.ensureDir(nexusPath);
    }

    // ── STEP 5: Inject README
    await fs.writeFile(
        path.join(targetPath, 'README.md'),
        `# ${projectName}\n${sectionConfig.title} — TALL Stack Sandbox.\nTags: ${sectionConfig.tags.join(', ')}\nGenerated by Nexus Autonomous Pipeline.`
    );

    // ── STEP 6: Migrate database
    console.log(`   🗄️  Migrating SQLite database...`);
    const dbPath = path.join(targetPath, 'database', 'database.sqlite');
    await fs.remove(dbPath).catch(() => {});
    await fs.writeFile(dbPath, '');
    try {
        execSync('php artisan migrate:fresh --force', { cwd: targetPath, stdio: 'ignore' });
        console.log(`   ✅ Database migrated.`);
    } catch (e) {
        console.warn(`   ⚠️  Migrate failed (non-fatal): ${e.message.slice(0, 80)}`);
    }

    // ── STEP 7: Reset cycle counter
    piper.resetCycleCounter();

    // ── STEP 8: Nexus Autonomous Cycle
    console.log(`   🤖 Starting Nexus Autonomous Cycle (mode: ${sectionConfig.mode})...`);
    const engine = new NexusEngine({ rootPath: targetPath });
    await engine.runCycle({ mode: sectionConfig.mode, allowSensitive: true });

    // ── STEP 9: Harvest
    console.log(`   🌾 Harvesting knowledge to Golden HUB...`);
    await engine.harvest(targetPath);

    console.log(`\n🚀 FULL TALL APP READY - ${projectName}`);
    console.log(`📁 Path: ${targetPath}`);
    console.log(`🌐 Akses: http://localhost:8000 (login: admin@example.com / password)`);
    console.log(`💻 Perintah: npm run serve:tall`);
    console.log(`✅ [${projectName}] pipeline complete.\n`);
}

async function runSection() {
    console.log('\n╔══════════════════════════════════════════════════════╗');
    console.log(`║  🚀 NEXUS — ${sectionConfig.title} `);
    console.log(`║  ${sectionConfig.projects.length} Projects | TALL Stack | Autonomous Pipeline`);
    console.log('╚══════════════════════════════════════════════════════╝\n');

    if (!(await fs.pathExists(TEMPLATE_SOURCE))) {
        console.error(`❌ Template tidak ditemukan: ${TEMPLATE_SOURCE}`);
        process.exit(1);
    }

    const piper = new EvolutionPiper(ROOT_PATH);
    let success = 0, failed = 0;

    for (const projectName of sectionConfig.projects) {
        try {
            await setupTALLProject(projectName, piper);
            success++;
        } catch (err) {
            console.error(`\n❌ GAGAL [${projectName}]: ${err.message}`);
            failed++;
        }
    }

    console.log(`\n${'='.repeat(56)}`);
    console.log(`📊 SECTION ${sectionArg} SELESAI: ${success} berhasil, ${failed} gagal`);
    console.log(`${'='.repeat(56)}\n`);

    if (failed > 0) process.exit(1);
    process.exit(0);
}

runSection().catch(err => {
    console.error(`❌ Fatal error di setup_dynamic_section.js:`, err);
    process.exit(1);
});
