// tests/TDD/setup_dynamic_section.js
// NEXUS DYNAMIC SANDBOX PIPELINE
// Handles Sections 4 through 10 dynamically.

const fs = require('fs-extra');
const path = require('path');
const { execSync } = require('child_process');
const NexusEngine = require('../../agent/core/NexusEngine');
const EvolutionPiper = require('../../agent/core/EvolutionPiper');

const TEMPLATE_SOURCE = path.join(__dirname, '..', 'sandboxes', 'url-shortener');
const SANDBOXES_DIR   = path.join(__dirname, '..', 'sandboxes');
const ROOT_PATH       = path.join(__dirname, '..', '..');

const projectsData = require('./100-projects-data.js');

const sectionArg = process.argv[2];
if (!sectionArg || !projectsData[sectionArg]) {
    console.error(`❌ Harap berikan argumen section yang valid (4-10).`);
    process.exit(1);
}

const sectionConfig = projectsData[sectionArg];

async function setupTALLProject(projectName, piper) {
    const targetPath = path.join(SANDBOXES_DIR, projectName);

    console.log(`\n${'='.repeat(56)}`);
    console.log(`🚀 [SECTION ${sectionArg}] PROJECT: ${projectName}`);
    console.log(`🏷️  Tags: ${sectionConfig.tags.join(', ')}`);
    console.log(`${'='.repeat(56)}`);

    // ── STEP 1: Backup nexus knowledge
    const nexusPath   = path.join(targetPath, 'nexus');
    const nexusBackup = path.join(targetPath, '_nexus_backup');
    if (await fs.pathExists(nexusPath)) {
        console.log(`   💾 Backing up nexus knowledge...`);
        await fs.copy(nexusPath, nexusBackup);
    }

    // ── STEP 2: Copy TALL stack template (url-shortener sebagai base)
    console.log(`   📂 Copying TALL stack template...`);
    const hasDeps = await fs.pathExists(path.join(targetPath, 'node_modules'));
    const hasVendor = await fs.pathExists(path.join(targetPath, 'vendor'));
    
    const tempDeps = path.join(targetPath, '..', `${projectName}_node_modules_temp`);
    const tempVendor = path.join(targetPath, '..', `${projectName}_vendor_temp`);
    
    if (hasDeps) {
        await fs.rename(path.join(targetPath, 'node_modules'), tempDeps).catch(() => {});
    }
    if (hasVendor) {
        await fs.rename(path.join(targetPath, 'vendor'), tempVendor).catch(() => {});
    }

    if (await fs.pathExists(targetPath)) {
        await fs.remove(targetPath).catch(() => {});
    }
    await fs.ensureDir(targetPath);

    const orchestratorPath = path.join(ROOT_PATH, 'nexus', 'native', 'sandbox_orchestrator.exe');
    let nativeCopySuccess = false;

    if (await fs.pathExists(orchestratorPath)) {
        try {
            console.log(`   🚀 Invoking C++ Native Sandbox Orchestrator...`);
            const { execSync } = require('child_process');
            execSync(`"${orchestratorPath}" setup "${TEMPLATE_SOURCE}" "${targetPath}" "${projectName}"`, { stdio: 'ignore' });
            nativeCopySuccess = true;
        } catch (e) {
            console.warn(`   ⚠️ Native copy failed: ${e.message}. Falling back to JS copy.`);
        }
    }

    if (!nativeCopySuccess) {
        await fs.copy(TEMPLATE_SOURCE, targetPath, {
            filter: src => {
                if (src.includes(path.join('url-shortener', 'nexus'))) return false;
                if (hasDeps && /(\\|\/)(node_modules)(\\|\/|$)/.test(src)) return false;
                if (hasVendor && /(\\|\/)(vendor)(\\|\/|$)/.test(src)) return false;
                return true;
            }
        });
    }

    // Restore node_modules & vendor if they were backed up
    if (hasDeps && await fs.pathExists(tempDeps)) {
        await fs.rename(tempDeps, path.join(targetPath, 'node_modules')).catch(() => {});
    }
    if (hasVendor && await fs.pathExists(tempVendor)) {
        await fs.rename(tempVendor, path.join(targetPath, 'vendor')).catch(() => {});
    }

    // ── STEP 3: Konfigurasi .env
    console.log(`   ⚙️  Configuring environment...`);
    const envPath = path.join(targetPath, '.env');
    if (await fs.pathExists(envPath)) {
        let env = await fs.readFile(envPath, 'utf8');
        env = env.replace(/APP_NAME=.*/g, `APP_NAME=${projectName}`);
        await fs.writeFile(envPath, env);
    }

    // ── STEP 4: Restore nexus knowledge
    if (await fs.pathExists(nexusBackup)) {
        await fs.copy(nexusBackup, nexusPath);
        await fs.remove(nexusBackup);
    } else {
        await fs.ensureDir(nexusPath);
    }

    // ── STEP 5: Inject README
    await fs.writeFile(
        path.join(targetPath, 'README.md'),
        `# ${projectName}\n${sectionConfig.title} — TALL Stack Sandbox.\nTags: ${sectionConfig.tags.join(', ')}\nGenerated by Nexus Autonomous Pipeline.`
    );

    // ── STEP 6: Migrate database
    console.log(`   🗄️  Migrating SQLite database...`);
    const dbPath = path.join(targetPath, 'database', 'database.sqlite');
    await fs.remove(dbPath).catch(() => {});
    await fs.writeFile(dbPath, '');
    try {
        execSync('php artisan migrate:fresh --force', { cwd: targetPath, stdio: 'ignore' });
        console.log(`   ✅ Database migrated.`);
    } catch (e) {
        console.warn(`   ⚠️  Migrate failed (non-fatal): ${e.message.slice(0, 80)}`);
    }

    // ── STEP 7: Reset cycle counter
    piper.resetCycleCounter();

    // ── STEP 8: Nexus Autonomous Cycle
    console.log(`   🤖 Starting Nexus Autonomous Cycle (mode: ${sectionConfig.mode})...`);
    const engine = new NexusEngine({ rootPath: targetPath });
    await engine.runCycle({ mode: sectionConfig.mode, allowSensitive: true });

    // ── STEP 8.5: Clean Code & Stability Verification Loop (5x)
    await engine.cleanCodeAndVerify(targetPath);

    // ── STEP 9: Harvest
    console.log(`   🌾 Harvesting knowledge to Golden HUB...`);
    await engine.harvest(targetPath);

    console.log(`\n🚀 FULL TALL APP READY - ${projectName}`);
    console.log(`📁 Path: ${targetPath}`);
    console.log(`🌐 Akses: http://localhost:8000 (login: admin@example.com / password)`);
    console.log(`💻 Perintah: npm run serve:tall`);
    console.log(`✅ [${projectName}] pipeline complete.\n`);
}

async function runSection() {
    console.log('\n╔══════════════════════════════════════════════════════╗');
    console.log(`║  🚀 NEXUS — ${sectionConfig.title} `);
    console.log(`║  ${sectionConfig.projects.length} Projects | TALL Stack | Autonomous Pipeline`);
    console.log('╚══════════════════════════════════════════════════════╝\n');

    if (!(await fs.pathExists(TEMPLATE_SOURCE))) {
        console.error(`❌ Template tidak ditemukan: ${TEMPLATE_SOURCE}`);
        process.exit(1);
    }

    const piper = new EvolutionPiper(ROOT_PATH);
    const total = sectionConfig.projects.length; // Run all projects
    let success = 0, failed = 0;
    const startTime = Date.now();

    for (let i = 0; i < total; i++) {
        const projectName = sectionConfig.projects[i];
        const elapsed = Math.round((Date.now() - startTime) / 1000);
        const eta = i > 0 ? Math.round((elapsed / i) * (total - i)) : '?';
        const pct = Math.round(((i + 1) / total) * 100);
        const bar = '█'.repeat(Math.floor(pct / 5)) + '░'.repeat(20 - Math.floor(pct / 5));

        console.log(`\n\x1b[35m[${bar}] ${pct}% | ✅ ${success} ❌ ${failed} | Project ${i + 1}/${total}: ${projectName} | ETA: ${eta}s\x1b[0m`);

        try {
            await setupTALLProject(projectName, piper);
            success++;
        } catch (err) {
            console.error(`\n\x1b[31m❌ GAGAL [${projectName}]: ${err.message}\x1b[0m`);
            failed++;
            // Log to error file
            const logFile = path.join(ROOT_PATH, 'logs', 'sandbox-errors.log');
            await fs.ensureDir(path.dirname(logFile));
            await fs.appendFile(logFile, `[${new Date().toISOString()}] [Section ${sectionArg}] [${projectName}] ${err.message}\n`);
        }
    }

    const totalElapsed = Math.round((Date.now() - startTime) / 1000);
    console.log(`\n${'='.repeat(56)}`);
    console.log(`📊 SECTION ${sectionArg} SELESAI: ${success} berhasil, ${failed} gagal`);
    console.log(`⏱  Total waktu: ${totalElapsed}s`);
    console.log(`${'='.repeat(56)}\n`);

    if (failed > 0) process.exit(1);
    process.exit(0);
}

runSection().catch(err => {
    console.error(`❌ Fatal error di setup_dynamic_section.js:`, err);
    process.exit(1);
});
