const fs = require('fs-extra');
const path = require('path');

/**
 * Modifier - The "Muscles" of the Nexus Engine.
 * Handles atomic file operations requested by the Orchestrator.
 */
class Modifier {
    constructor(rootPath) {
        this.rootPath = rootPath;
    }

    /**
     * Apply an action to the file system
     * @param {Object} action - { type, target, content, replacement }
     */
    async apply(action) {
        if (!action || !action.type) return false;

        const targetPath = path.resolve(this.rootPath, action.target);
        
        // Security Guard: Prevent writing outside root
        if (!targetPath.startsWith(this.rootPath)) {
            throw new Error(`Security Violation: Attempted to write outside project root: ${action.target}`);
        }

        switch (action.type) {
            case 'FILE_CREATE':
                return await this.fileCreate(targetPath, action.content);
            case 'FILE_APPEND':
                return await this.fileAppend(targetPath, action.content);
            case 'FILE_REPLACE':
                return await this.fileReplace(targetPath, action.targetContent, action.replacementContent);
            case 'BATCH_REPLACE':
                return await this.batchReplace(targetPath, action.replacements);
            case 'RESOLVE_OPTIONS':
                return await this.resolveOptions(targetPath, action.choice);
            case 'LARAVEL_INJECT_TRAIT':
                return await this.injectTrait(targetPath, action.namespace, action.trait);
            case 'LARAVEL_ADD_COLUMN':
                return await this.addMigrationColumn(targetPath, action.definition);
            case 'ENV_ENSURE':
                return await this.ensureEnv(targetPath, action.key, action.value);
            case 'COMMAND_EXEC':
                const ALLOWED_COMMANDS = ['composer', 'php', 'npm', 'node'];
                const cmdParts = action.command.split(' ');
                const cmdBase = path.basename(cmdParts[0]);
                if (!ALLOWED_COMMANDS.includes(cmdBase)) {
                    throw new Error(`COMMAND_EXEC Security Violation: Command "${cmdBase}" is not allowed.`);
                }
                await this.spawnAsync(cmdBase, cmdParts.slice(1), { cwd: this.rootPath, stdio: 'ignore' });
                return true;
            default:
                throw new Error(`Unknown action type: ${action.type}`);
        }
    }

    /**
     * Resolve a Multi-Option block into a single chosen path.
     * @param {string} filePath 
     * @param {string} choice - 'A' or 'B'
     */
    async resolveOptions(filePath, choice = 'A') {
        if (!(await fs.pathExists(filePath))) throw new Error(`File not found: ${filePath}`);
        
        let content = await fs.readFile(filePath, 'utf8');
        
        // Regex to capture the Multi-Option blocks and the whole collision section
        const regexA = /#### Opsi A: [^\n]*\n([\s\S]*?)(?=\n---)/;
        const regexB = /#### Opsi B: [^\n]*\n([\s\S]*?)(?=\n---)/;
        
        // This matches the entire generated collision block including the footer
        const finalRegex = /### 🧩 Pilihan Opsi Tak Terbatas:[\s\S]*?\*(?:Generated by Nexus Engine|Merged by Nexus Distiller).*?\*/s;

        const matchA = content.match(regexA);
        const matchB = content.match(regexB);
        
        if (!matchA || !matchB) {
             throw new Error(`Multi-Option block not found or malformed in ${filePath}`);
        }

        const selectedContent = (choice.toUpperCase() === 'A') ? matchA[1].trim() : matchB[1].trim();
        
        if (content.match(finalRegex)) {
            const newContent = content.replace(finalRegex, selectedContent);
            await fs.writeFile(filePath, newContent.trim());
            return true;
        }
        
        return false;
    }

    /**
     * Perform multiple replacements in a single file
     * @param {string} filePath 
     * @param {Array} replacements - Array of { target, replacement }
     */
    async batchReplace(filePath, replacements) {
        if (!(await fs.pathExists(filePath))) throw new Error(`File not found: ${filePath}`);
        
        let content = await fs.readFile(filePath, 'utf8');
        let modified = false;

        for (const r of replacements) {
            if (content.includes(r.target)) {
                content = content.replace(new RegExp(this.escapeRegExp(r.target), 'g'), r.replacement);
                modified = true;
            }
        }

        if (modified) {
            await fs.writeFile(filePath, content);
            return true;
        }
        return false;
    }

    escapeRegExp(string) {
        return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    }

    async fileCreate(filePath, content) {
        await fs.ensureDir(path.dirname(filePath));
        await fs.writeFile(filePath, content || '');
        return true;
    }

    async fileAppend(filePath, content) {
        if (await fs.pathExists(filePath)) {
            await fs.appendFile(filePath, `\n${content}`);
            return true;
        }
        return await this.fileCreate(filePath, content);
    }

    async spawnAsync(cmd, args, options = {}) {
        return new Promise((resolve, reject) => {
            const { spawn } = require('child_process');
            const child = spawn(cmd, args, options);
            child.on('close', (code) => {
                if (code === 0) resolve();
                else reject(new Error(`Command ${cmd} exited with code ${code}`));
            });
            child.on('error', (err) => reject(err));
        });
    }

    async fileReplace(filePath, targetContent, replacementContent) {
        if (await fs.pathExists(filePath)) {
            let content = await fs.readFile(filePath, 'utf8');
            if (content.includes(targetContent)) {
                const newContent = content.replace(targetContent, replacementContent);
                await fs.writeFile(filePath, newContent);
                return true;
            }
            
            // 2. Jika gagal, coba normalisasi whitespace & newline (fuzzy matching)
            const normalize = (str) => str.replace(/\s+/g, ' ').trim();
            const normalizedContent = normalize(content);
            const normalizedTarget = normalize(targetContent);
            
            if (normalizedContent.includes(normalizedTarget)) {
                const escapedTarget = this.escapeRegExp(targetContent.trim()).replace(/\\s+/g, '\\s+');
                const regex = new RegExp(escapedTarget);
                if (regex.test(content)) {
                    const newContent = content.replace(regex, replacementContent);
                    await fs.writeFile(filePath, newContent);
                    return true;
                }
            }
            
            throw new Error(`Target content not found in file: ${filePath}`);
        }
        throw new Error(`File not found: ${filePath}`);
    }

    /**
     * LARAVEL: Inject a Trait into a Model
     */
    async injectTrait(filePath, traitNamespace, traitName) {
        if (!(await fs.pathExists(filePath))) return false;
        let content = await fs.readFile(filePath, 'utf8');
        
        if (!content.includes(traitNamespace)) {
            content = content.replace(/namespace .*;/g, (match) => `${match}\nuse ${traitNamespace};`);
        }
        if (!content.includes(`use ${traitName};`)) {
            content = content.replace(/class .* {/g, (match) => `${match}\n    use ${traitName};`);
        }

        await fs.writeFile(filePath, content);
        return true;
    }

    /**
     * LARAVEL: Add a column to a migration
     */
    async addMigrationColumn(filePath, columnDefinition) {
        if (!(await fs.pathExists(filePath))) return false;
        let content = await fs.readFile(filePath, 'utf8');
        
        if (content.includes('$table->timestamps()')) {
            content = content.replace('$table->timestamps()', `${columnDefinition}\n            $table->timestamps()`);
        } else {
            content = content.replace(/}\);/g, `    ${columnDefinition}\n        });`);
        }

        await fs.writeFile(filePath, content);
        return true;
    }

    /**
     * GENERAL: Ensure environment variable exists
     */
    async ensureEnv(envFile, key, value) {
        let content = (await fs.pathExists(envFile)) ? await fs.readFile(envFile, 'utf8') : '';

        if (content.includes(`${key}=`)) {
            content = content.replace(new RegExp(`${key}=.*`, 'g'), `${key}=${value}`);
        } else {
            content += `\n${key}=${value}`;
        }

        await fs.writeFile(envFile, content.trim() + '\n');
        return true;
    }
}

module.exports = Modifier;
