import os
import torch
from datasets import load_dataset
from unsloth import FastLanguageModel
from trl import SFTTrainer
from transformers import TrainingArguments

# ==============================================================================
# NEXUS AI - UNSLOTH QLORA FINE-TUNING SCRIPT
# ==============================================================================
# This script is designed to fine-tune a model using the JSONL dataset
# generated by the `nexus extract-dataset` command.
#
# Requirements:
# pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
# pip install --no-deps xformers trl peft accelerate bitsandbytes
# ==============================================================================

# Configuration
DATASET_PATH = "../memory/datasets/nexus-retro-dataset.jsonl"
MODEL_NAME = "unsloth/llama-3-8b-Instruct-bnb-4bit" # Base model
MAX_SEQ_LENGTH = 4096
OUTPUT_DIR = "../memory/models/nexus-coder-v1"

if not os.path.exists(DATASET_PATH):
    print(f"❌ Dataset not found at: {DATASET_PATH}")
    print("Please run `bun cli.js extract-dataset` first.")
    exit(1)

print("🚀 Initializing Unsloth FastLanguageModel...")

# 1. Load Model & Tokenizer
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = MODEL_NAME,
    max_seq_length = MAX_SEQ_LENGTH,
    dtype = None, # Auto detection
    load_in_4bit = True,
)

# 2. Add LoRA Adapters
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
    use_rslora = False,
    loftq_config = None,
)

# 3. Format Dataset
# We convert the instruction and output into the format expected by the model.
prompt_template = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Response:
{}"""

EOS_TOKEN = tokenizer.eos_token
def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    outputs      = examples["output"]
    texts = []
    for instruction, output in zip(instructions, outputs):
        text = prompt_template.format(instruction, output) + EOS_TOKEN
        texts.append(text)
    return { "text" : texts, }

print(f"📂 Loading dataset from {DATASET_PATH}")
dataset = load_dataset("json", data_files=DATASET_PATH, split="train")
dataset = dataset.map(formatting_prompts_func, batched = True)

# 4. Train Model
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = MAX_SEQ_LENGTH,
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60, # Change to num_epochs = 1 for full training
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
    ),
)

print("🔥 Starting training...")
trainer_stats = trainer.train()
print("✅ Training complete!")

# 5. Save the LoRA weights
print(f"💾 Saving LoRA adapter to {OUTPUT_DIR}")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("\n🎉 DONE!")
print(f"You can now merge this model to GGUF using llama.cpp or Unsloth's export utilities.")
print("Example to export to GGUF directly via Unsloth:")
print(f"  model.save_pretrained_gguf('{OUTPUT_DIR}-gguf', tokenizer, quantization_method = 'q4_k_m')")
